### ISSUE TITLE
Unit testing with statick

### ISSUE THREAD

**Issue by tdenewiler** [tdenewiler/statick-tex#3]
I'm using this repo in part to address sscpac/statick#70. @creffett, I was hoping to get a bit of help from you in order to get the unit tests working. I borrowed some concepts for these plugins from soartech/statick-fortify. My latest work is in the chktex-tool  branch -- I will likely merge that into master soon since the plugins work but the unit tests do not.

The issue I am having is running tox locally, where I get several errors similar to:

```
=========================================================================================== ERRORS ===========================================================================================
__________________________________________________________ ERROR collecting statick_tool/plugins/discovery/tex_discovery_plugin.py ___________________________________________________________
../statick_tool/plugins/discovery/tex_discovery_plugin.py:10: in <module>
    from statick_tool.discovery_plugin import DiscoveryPlugin
E   ImportError: No module named 'statick_tool.discovery_plugin'
______________________________________________________________ ERROR collecting statick_tool/plugins/tool/chktex_tool_plugin.py ______________________________________________________________
../statick_tool/plugins/tool/chktex_tool_plugin.py:8: in <module>
    from statick_tool.issue import Issue
E   ImportError: No module named 'statick_tool.issue'
_____________________________________________________________ ERROR collecting statick_tool/plugins/tool/lacheck_tool_plugin.py ______________________________________________________________
../statick_tool/plugins/tool/lacheck_tool_plugin.py:8: in <module>
    from statick_tool.issue import Issue
E   ImportError: No module named 'statick_tool.issue'
_________________________________________________ ERROR collecting tests/plugins/discovery/tex_discovery_plugin/test_tex_discovery_plugin.py _________________________________________________
../tests/plugins/discovery/tex_discovery_plugin/test_tex_discovery_plugin.py:5: in <module>
    from statick_tool.discovery_plugin import DiscoveryPlugin
E   ImportError: No module named 'statick_tool.discovery_plugin'
_________________________________________________ ERROR collecting tests/plugins/discovery/tex_discovery_plugin/test_tex_discovery_plugin.py _________________________________________________
ImportError while importing test module '/home/thomas/src/statick/statick-tex/tests/plugins/discovery/tex_discovery_plugin/test_tex_discovery_plugin.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../tests/plugins/discovery/tex_discovery_plugin/test_tex_discovery_plugin.py:5: in <module>
    from statick_tool.discovery_plugin import DiscoveryPlugin
E   ImportError: No module named 'statick_tool.discovery_plugin'
```

When I run this through Travis I get other errors. Examples of the tox output and self check errors are at:

https://travis-ci.org/tdenewiler/statick-tex/jobs/512740453
https://travis-ci.org/tdenewiler/statick-tex/jobs/512740458

Did you come up with a solution to running tox locally and in Travis when writing plugins in a separate repository?

P.S. I will work on expanding the README a lot to help others make plugins in the future, much like what is discussed in sscpac/statick#70.

**Comment by tdenewiler** [comment]
I am making some progress on this. Hold off on doing extra work just yet.

**Comment by tdenewiler** [comment]
The errors I get now are from running `tox` locally, and the same errors are showing up in Travis. They are of the form:

```
>       assert any(plugin_info.plugin_object.get_name() == 'tex' for
                   plugin_info in manager.getPluginsOfCategory("Discovery"))
E       assert False
E        +  where False = any(<generator object test_tex_discovery_plugin_found.<locals>.<genexpr> at 0x7fab84706fc0>)
```

I started printing out the plugins that are found and my new ones are not found. I don't know if you have time to look, but if you can see what I'm doing wrong I'd appreciate a pointer.

https://travis-ci.org/tdenewiler/statick-tex/builds/515709831

**Comment by creffett** [comment]
Sure, I'll take a look on Monday.

**Comment by creffett** [comment]
Found it - setup.py is installing `*.yapsy_plugin` instead of `*.yapsy-plugin`.

**Comment by tdenewiler** [comment]
You are awesome. It is passing everything locally and at Travis now. Thanks!

https://travis-ci.org/tdenewiler/statick-tex/builds/518029962
